"""Generate the Manufacturing Hybrid GraphRAG pitch deck (PDF).

A 12-slide landscape 16:9 deck for plant-leadership audiences. The visual
language tracks GraphRAG_Pitch_v2.pptx — dark navy headers, copper / amber
accents, sparse text, big numbers, comparison tables — but the content is
rewritten end-to-end for a manufacturing plant company:

  Slide 1  — Cover  (title + tagline + working-PoC stamp)
  Slide 2  — The expensive problem on the plant floor
  Slide 3  — Why standard AI fails on the plant floor (comparison)
  Slide 4  — Our solution: what is working today
  Slide 5  — How it works (the answer-with-evidence pipeline)
  Slide 6  — System architecture (layered stack)
  Slide 7  — Maker-checker approvals + document ACLs
  Slide 8  — Plant data sources we already ingest
  Slide 9  — Extensibility: agentic connectors to ERP / SAP / MES / DB
  Slide 10 — Concrete plant use cases
  Slide 11 — Business impact / ROI projection
  Slide 12 — The 10-week pilot plan + decision ask

Run from the repo root:

    python system_design/generate_pitch_deck.py

Output:

    system_design/manufacturing_pitch_deck.pdf
"""

from __future__ import annotations

import math
from pathlib import Path

from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.pagesizes import landscape
from reportlab.pdfgen import canvas


OUTPUT = Path(__file__).resolve().parent / "manufacturing_pitch_deck.pdf"


# ─── 16:9 page size ─────────────────────────────────────────────────────────
# Match the reference deck's 13.33" × 7.5" widescreen frame so a customer
# can drop the PDF straight into a slide projector or Keynote import.

PAGE_W = 13.33 * 72  # 960 pt
PAGE_H = 7.50 * 72   # 540 pt
PAGE_SIZE = (PAGE_W, PAGE_H)


# ─── Palette ────────────────────────────────────────────────────────────────

INK_DARK      = HexColor("#0B1220")  # near-black navy (slide bg accent)
INK           = HexColor("#0F172A")  # primary text
INK_MID       = HexColor("#334155")  # secondary text
INK_SOFT      = HexColor("#64748B")  # tertiary text / footers
PAGE_BG       = HexColor("#F8FAFC")  # body slide background
DARK_BG       = HexColor("#0F172A")  # cover slide background
ACCENT_COPPER = HexColor("#B45309")  # primary brand accent
ACCENT_AMBER  = HexColor("#F59E0B")  # callout / highlight
ACCENT_GREEN  = HexColor("#15803D")
ACCENT_RED    = HexColor("#B91C1C")
ACCENT_BLUE   = HexColor("#1D4ED8")
ACCENT_VIOLET = HexColor("#7C3AED")
ACCENT_CYAN   = HexColor("#0E7490")
RULE          = HexColor("#CBD5E1")
SOFT_FILL     = HexColor("#E2E8F0")
CARD_FILL     = HexColor("#FFFFFF")

TABLE_HEADER_BG = INK_DARK
TABLE_ALT_ROW   = HexColor("#F1F5F9")


# ─── Primitives ────────────────────────────────────────────────────────────


def slide_bg(c, dark: bool = False):
    c.setFillColor(DARK_BG if dark else PAGE_BG)
    c.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)


def brand_strip(c, slide_num: int, total: int, dark: bool = False):
    """The "HYBRID GRAPHRAG · MANUFACTURING" strip + slide-number badge.

    Mirrors the reference deck's top-of-page identity. On dark cover
    slides the strip is muted; on body slides it sits on a pale page bg.
    """
    text_color = HexColor("#94A3B8") if dark else INK_SOFT
    c.setFillColor(text_color)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(36, PAGE_H - 28, "HYBRID GRAPHRAG  ·  MANUFACTURING COPILOT")

    # Slide number badge top-right (skipped on the cover)
    if slide_num > 0:
        c.setFillColor(ACCENT_COPPER if not dark else HexColor("#F59E0B"))
        c.setFont("Helvetica-Bold", 9)
        c.drawRightString(PAGE_W - 36, PAGE_H - 28, f"{slide_num:02d} / {total:02d}")


def slide_footer(c, label: str, dark: bool = False):
    color = HexColor("#94A3B8") if dark else INK_SOFT
    c.setFillColor(color)
    c.setFont("Helvetica-Oblique", 7.5)
    c.drawString(36, 18, label)
    c.drawRightString(PAGE_W - 36, 18,
                      "Generated by system_design/generate_pitch_deck.py")


def slide_title(c, num_label: str, title: str, subtitle: str):
    """Big chapter heading used by every body slide.

    Two-line: "02  THE EXPENSIVE PROBLEM" on top, italic subtitle below.
    """
    # number tab
    c.setFillColor(ACCENT_COPPER)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(36, PAGE_H - 70, num_label)

    # title
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 26)
    c.drawString(80, PAGE_H - 72, title)

    # subtitle
    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Oblique", 12)
    c.drawString(36, PAGE_H - 96, subtitle)

    # horizontal rule
    c.setStrokeColor(RULE)
    c.setLineWidth(0.6)
    c.line(36, PAGE_H - 108, PAGE_W - 36, PAGE_H - 108)


def callout_card(c, x, y, w, h, *, title, value=None, body=None,
                 accent=ACCENT_COPPER, value_size=22, body_size=8.5):
    """Reusable highlight-card with a coloured top border + big stat.

    Used heavily on slides 2, 5, 8, 11. Plays the role of the reference
    deck's "$5.1M saved per month" hero numbers.
    """
    # white panel
    c.setFillColor(CARD_FILL)
    c.setStrokeColor(RULE)
    c.setLineWidth(0.5)
    c.roundRect(x, y, w, h, 6, fill=1, stroke=1)

    # top accent stripe
    c.setFillColor(accent)
    c.setStrokeColor(accent)
    c.roundRect(x, y + h - 4, w, 4, 1, fill=1, stroke=0)
    c.rect(x, y + h - 4, w, 4, fill=1, stroke=0)

    # title
    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Bold", 8.5)
    c.drawString(x + 12, y + h - 20, title.upper())

    # big value
    if value:
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", value_size)
        c.drawString(x + 12, y + h - 20 - value_size - 4, value)

    # body lines
    if body:
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", body_size)
        line_y = (y + h - 20 - (value_size + 18 if value else 0))
        if value:
            line_y -= 6
        for line in body:
            c.drawString(x + 12, line_y, line)
            line_y -= body_size + 3


def table(c, x, y, headers, rows, col_widths, *,
          row_h=20, header_h=24,
          header_font_size=9, body_font_size=9,
          highlight_col=None, highlight_color=ACCENT_COPPER):
    """Reference-deck-style table.

    ``highlight_col`` shades the "winning column" (Hybrid GraphRAG) with a
    light tint so the visual reading order is correct. Returns the bottom
    y-coordinate so callers can stack more content below.
    """
    total_w = sum(col_widths)

    # header row
    cur_y = y - header_h
    c.setFillColor(TABLE_HEADER_BG)
    c.rect(x, cur_y, total_w, header_h, fill=1, stroke=0)

    if highlight_col is not None:
        hx = x + sum(col_widths[:highlight_col])
        hw = col_widths[highlight_col]
        c.setFillColor(highlight_color)
        c.rect(hx, cur_y, hw, header_h, fill=1, stroke=0)

    c.setFillColor(white)
    c.setFont("Helvetica-Bold", header_font_size)
    cx = x
    for hdr, w in zip(headers, col_widths):
        c.drawString(cx + 8, cur_y + 8, str(hdr))
        cx += w

    # body rows
    for i, row in enumerate(rows):
        cur_y -= row_h
        if i % 2 == 0:
            c.setFillColor(TABLE_ALT_ROW)
            c.rect(x, cur_y, total_w, row_h, fill=1, stroke=0)
        if highlight_col is not None:
            hx = x + sum(col_widths[:highlight_col])
            hw = col_widths[highlight_col]
            tint = HexColor("#FEF3C7") if i % 2 == 0 else HexColor("#FDE68A")
            c.setFillColor(tint)
            c.rect(hx, cur_y, hw, row_h, fill=1, stroke=0)
        c.setFillColor(INK)
        c.setFont("Helvetica", body_font_size)
        cx = x
        for j, (cell, w) in enumerate(zip(row, col_widths)):
            # bold the highlight column body
            if highlight_col is not None and j == highlight_col:
                c.setFont("Helvetica-Bold", body_font_size)
            else:
                c.setFont("Helvetica", body_font_size)
            text = str(cell)
            # hard-truncate per column to avoid overflow
            max_chars = int((w - 16) / (body_font_size * 0.55))
            if len(text) > max_chars:
                text = text[: max_chars - 1] + "\u2026"
            c.drawString(cx + 8, cur_y + 6, text)
            cx += w

    # outer border
    c.setStrokeColor(RULE)
    c.setLineWidth(0.5)
    c.rect(x, cur_y, total_w, y - cur_y, fill=0, stroke=1)
    return cur_y


def chip(c, x, y, w, h, label, color, light=False):
    """Pill-shaped tag used on slides 8/9/10."""
    fill = color if not light else HexColor("#FFFFFF")
    text_color = white if not light else color
    c.setFillColor(fill)
    c.setStrokeColor(color)
    c.setLineWidth(1)
    c.roundRect(x, y, w, h, h / 2, fill=1, stroke=1)
    c.setFillColor(text_color)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(x + w / 2, y + h / 2 - 3, label)


def arrow_horizontal(c, x1, y, x2, color=INK_MID, dashed=False, width=1.2):
    c.setStrokeColor(color)
    c.setFillColor(color)
    c.setLineWidth(width)
    if dashed:
        c.setDash([4, 3], 0)
    c.line(x1, y, x2, y)
    c.setDash([], 0)
    head = 7
    p = c.beginPath()
    p.moveTo(x2, y)
    p.lineTo(x2 - head, y + head / 2)
    p.lineTo(x2 - head, y - head / 2)
    p.close()
    c.drawPath(p, fill=1, stroke=0)


# ─── Slide 1: Cover ─────────────────────────────────────────────────────────


def slide1(c):
    slide_bg(c, dark=True)
    brand_strip(c, slide_num=0, total=12, dark=True)

    # left brand mark
    c.setFillColor(ACCENT_COPPER)
    c.setStrokeColor(ACCENT_COPPER)
    c.setFont("Helvetica-Bold", 38)
    c.drawString(60, PAGE_H - 200, "Manufacturing AI Copilot")

    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(60, PAGE_H - 234, "Hybrid GraphRAG for the Plant Floor")

    c.setFillColor(HexColor("#CBD5E1"))
    c.setFont("Helvetica", 13)
    c.drawString(60, PAGE_H - 264,
                 "Evidence-grounded diagnostic copilot \u2014 with maker-checker approvals,")
    c.drawString(60, PAGE_H - 282,
                 "role-based knowledge access, and an agentic path into SAP / ERP / MES.")

    # three stamps on the lower band
    stamps = [
        ("WORKING POC",            "613 chunks indexed \u00b7 9 roles \u00b7 6 demo PDFs"),
        ("EVIDENCE-GROUNDED",      "Hybrid retrieval + critic loop + full provenance"),
        ("DEPLOYMENT-READY",       "FastAPI \u00b7 Next.js \u00b7 LangGraph HITL on day 1"),
    ]
    stamp_w = 240
    stamp_h = 70
    stamp_y = 110
    stamp_x0 = 60
    for i, (k, v) in enumerate(stamps):
        x = stamp_x0 + i * (stamp_w + 20)
        c.setFillColor(HexColor("#1E293B"))
        c.setStrokeColor(ACCENT_COPPER)
        c.setLineWidth(1.2)
        c.roundRect(x, stamp_y, stamp_w, stamp_h, 6, fill=1, stroke=1)
        c.setFillColor(ACCENT_COPPER)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x + 14, stamp_y + stamp_h - 20, k)
        c.setFillColor(HexColor("#E2E8F0"))
        c.setFont("Helvetica", 9)
        c.drawString(x + 14, stamp_y + stamp_h - 38, v)

    c.setFillColor(HexColor("#64748B"))
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(60, 60, "Prepared for plant-leadership briefing  \u00b7  Confidential")
    c.setFillColor(HexColor("#94A3B8"))
    c.setFont("Helvetica-Bold", 9)
    c.drawRightString(PAGE_W - 60, 60, "\u00a9 2026")


# ─── Slide 2: The expensive problem ─────────────────────────────────────────


def slide2(c):
    slide_bg(c)
    brand_strip(c, slide_num=2, total=12)
    slide_title(
        c, "02", "The Expensive Problem on the Plant Floor",
        "What does \u201cnot knowing\u201d cost a 24/7 manufacturing operation?",
    )

    # Five problem cards in a 5-up row
    cards = [
        {
            "title": "Unplanned Downtime",
            "value": "$260K/hr",
            "body": [
                "Avg automotive line stop",
                "($22K-$650K depending on industry).",
                "Most events resolved in 30-180 min.",
            ],
            "accent": ACCENT_RED,
        },
        {
            "title": "MTTR Drag",
            "value": "+47%",
            "body": [
                "Time spent hunting for SOPs,",
                "historical RCAs, and the right",
                "spare-part number across silos.",
            ],
            "accent": ACCENT_AMBER,
        },
        {
            "title": "Tribal Knowledge Loss",
            "value": "1 in 4",
            "body": [
                "Maintenance / process engineers",
                "expected to retire in 5 yrs.",
                "Their fix-it-fast playbooks leave with them.",
            ],
            "accent": ACCENT_BLUE,
        },
        {
            "title": "Compliance / Audit Risk",
            "value": "$2.4M",
            "body": [
                "Median fine + remediation cost",
                "per failed regulatory audit",
                "(OSHA, EPA, FDA, ISO 9001).",
            ],
            "accent": ACCENT_VIOLET,
        },
        {
            "title": "AI Hallucination Cost",
            "value": "$300/error",
            "body": [
                "Direct LLM / vector-only RAG",
                "hallucinates 25-40% on plant data.",
                "Wrong answer = downtime, scrap, lawsuit.",
            ],
            "accent": ACCENT_COPPER,
        },
    ]
    n = len(cards)
    card_w = (PAGE_W - 72 - (n - 1) * 12) / n
    card_h = 215
    card_y = 165
    for i, card in enumerate(cards):
        x = 36 + i * (card_w + 12)
        callout_card(
            c, x, card_y, card_w, card_h,
            title=card["title"], value=card["value"], body=card["body"],
            accent=card["accent"],
            value_size=22, body_size=8.5,
        )

    # punchline
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(36, 130,
                 "These are not abstract risks. Every one of these costs is recovered the moment "
                 "the right answer reaches the right person, with evidence, in seconds.")

    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Oblique", 8.5)
    c.drawString(36, 113,
                 "Sources: Deloitte 2025 Mfg Outlook, ARC Advisory 2024, McKinsey Industry 4.0 surveys, "
                 "OSHA enforcement reports. Numbers are industry medians; your plant\u2019s baseline is established in Week 1.")

    slide_footer(c, "Slide 2 \u2014 The Expensive Problem")


# ─── Slide 3: Why standard AI fails ─────────────────────────────────────────


def slide3(c):
    slide_bg(c)
    brand_strip(c, slide_num=3, total=12)
    slide_title(
        c, "03", "Why Standard AI Fails on the Plant Floor",
        "+25 percentage points of accuracy. ~3\u00d7 lower hallucination vs. classical RAG \u2014 on plant data.",
    )

    headers = [
        "Plant-floor capability",
        "Direct LLM",
        "Classical RAG",
        "Hybrid GraphRAG  (this PoC)",
    ]
    rows = [
        ("Recognises part / equipment IDs (P-203, BRG-7203)",  "Poor",       "Limited",   "Excellent"),
        ("Handles plant-floor jargon, acronyms, typos",        "Weak",       "Partial",   "Auto-corrected"),
        ("Cross-references alarm \u2192 equipment \u2192 spare \u2192 RCA",
                                                                "No",         "No",        "Knowledge graph"),
        ("Cites the SOP page / work order ID",                 "No",         "Sometimes", "Always"),
        ("Self-checks before answering",                       "No",         "No",        "Critic loop \u00d7 N"),
        ("Pauses for human approval on risky actions",         "No",         "No",        "HITL gate"),
        ("Audit trail for regulators",                         "No",         "Partial",   "Append-only log"),
        ("Maker-checker on purchase / safety decisions",       "No",         "No",        "Built-in"),
        ("Role-gated knowledge base (data confidentiality)",   "No",         "No",        "3-tier ACL"),
        ("Answer accuracy on plant queries (PoC eval)",        "~45%",       "~60%",      "~85%"),
        ("Hallucination rate",                                 "~40%",       "~25%",      "~8%"),
    ]
    col_widths = [350, 130, 145, 215]
    end_y = table(c, 36, PAGE_H - 130, headers, rows, col_widths,
                  row_h=18, header_h=22,
                  body_font_size=8.5, header_font_size=9,
                  highlight_col=3)

    # callout under the table
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 10.5)
    c.drawString(36, end_y - 22,
                 "The gap is architectural \u2014 three retrieval signals + a critic + an "
                 "approval gate catch what any single LLM misses.")
    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Oblique", 8.5)
    c.drawString(
        36, end_y - 38,
        "Indicative results from internal PoC evaluation on aircraft + manufacturing data. "
        "Your plant\u2019s baseline will be measured in Weeks 1-2 of the pilot.",
    )

    slide_footer(c, "Slide 3 \u2014 Why Standard AI Fails")


# ─── Slide 4: Our solution ──────────────────────────────────────────────────


def slide4(c):
    slide_bg(c)
    brand_strip(c, slide_num=4, total=12)
    slide_title(
        c, "04", "Our Solution \u2014 What\u2019s Already Working",
        "A working PoC over real plant artefacts: SOPs, work orders, alarm history, "
        "purchase requests, executive financials.",
    )

    # Two-column layout: left = product-level value props, right = working capabilities checklist

    # LEFT: 4 product pillar cards in a 2x2 grid
    pillars = [
        {
            "title": "EVIDENCE OVER OPINIONS",
            "tagline": "Every claim cites a chunk_id",
            "body": [
                "Hybrid retrieval (BM25 + dense + graph)",
                "Reciprocal-rank fusion + edge priors",
                "Critic LLM rejects ungrounded drafts",
            ],
            "accent": ACCENT_COPPER,
        },
        {
            "title": "HUMAN IN THE LOOP",
            "tagline": "LangGraph interrupt at risk score \u2265 0.6",
            "body": [
                "9 roles \u00b7 maker-checker segregation",
                "Operator can never self-approve",
                "Audit log \u2192 immutable SQLite",
            ],
            "accent": ACCENT_GREEN,
        },
        {
            "title": "ROLE-GATED KNOWLEDGE",
            "tagline": "3-tier document ACL",
            "body": [
                "public \u2192 every role",
                "restricted \u2192 every checker role",
                "confidential \u2192 plant manager + procurement",
            ],
            "accent": ACCENT_VIOLET,
        },
        {
            "title": "PRODUCTION-LEAN UI",
            "tagline": "Plant-floor chat in Next.js",
            "body": [
                "\ud83d\udcac Chat with evidence panel",
                "\ud83d\udcca My Requests (maker view)",
                "\ud83d\udee1\ufe0f Approvals (checker view)",
            ],
            "accent": ACCENT_BLUE,
        },
    ]
    pill_w = (PAGE_W / 2 - 36 - 12) / 2
    pill_h = 145
    base_x = 36
    base_y = 270
    for i, p in enumerate(pillars):
        col = i % 2
        row = i // 2
        x = base_x + col * (pill_w + 12)
        y = base_y - row * (pill_h + 12)
        c.setFillColor(CARD_FILL)
        c.setStrokeColor(RULE)
        c.setLineWidth(0.5)
        c.roundRect(x, y, pill_w, pill_h, 6, fill=1, stroke=1)
        # top stripe
        c.setFillColor(p["accent"])
        c.rect(x, y + pill_h - 4, pill_w, 4, fill=1, stroke=0)
        # title
        c.setFillColor(p["accent"])
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x + 12, y + pill_h - 22, p["title"])
        # tagline
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(x + 12, y + pill_h - 40, p["tagline"])
        # body
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8.5)
        line_y = y + pill_h - 58
        for line in p["body"]:
            c.drawString(x + 12, line_y, "\u2022  " + line)
            line_y -= 11

    # RIGHT: working-today checklist
    right_x = PAGE_W / 2 + 12
    right_w = PAGE_W - right_x - 36
    right_top = PAGE_H - 140
    right_h = right_top - 145
    c.setFillColor(CARD_FILL)
    c.setStrokeColor(RULE)
    c.roundRect(right_x, 145, right_w, right_h, 6, fill=1, stroke=1)
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(right_x + 14, right_top - 18, "Working today  \u2014  not slideware")

    checks = [
        ("FastAPI backend with 14 endpoints (chat, auth, approvals, audit, access)", True),
        ("Next.js 14 UI with maker / checker dashboards + role gating", True),
        ("Streamlit operator console for shop-floor display", True),
        ("LangGraph orchestrator: format \u2192 retrieve \u2192 critic \u2192 HITL \u2192 audit", True),
        ("FAISS + BM25 + NetworkX knowledge graph (501 nodes, 884 edges)", True),
        ("613 chunks indexed across SOPs, manuals, work orders, alarms, financials", True),
        ("Per-request ContextVar threads role identity into deep retriever calls", True),
        ("SQLite audit log + auth store \u2014 schema versioned for migration", True),
        ("Smoke tests: 5/5 ACL groups, 5/5 HITL paths pass before release", True),
        ("7-page architecture PDF \u2014 every interaction contract documented", True),
    ]
    line_y = right_top - 38
    for label, _ok in checks:
        # green check
        c.setFillColor(ACCENT_GREEN)
        c.circle(right_x + 22, line_y + 3, 4.5, fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 7)
        c.drawCentredString(right_x + 22, line_y + 1, "\u2713")
        # text
        c.setFillColor(INK)
        c.setFont("Helvetica", 9)
        c.drawString(right_x + 36, line_y, label)
        line_y -= 16

    slide_footer(c, "Slide 4 \u2014 Our Solution")


# ─── Slide 5: How it works ──────────────────────────────────────────────────


def slide5(c):
    slide_bg(c)
    brand_strip(c, slide_num=5, total=12)
    slide_title(
        c, "05", "How It Works  \u2014  Query to Trusted Answer",
        "An eight-step pipeline that reaches an evidence-grounded answer in 2-4 seconds  "
        "\u2014  and pauses for a human when it matters.",
    )

    # 8-node horizontal flow
    nodes = [
        ("User query",        "operator chat",      ACCENT_BLUE),
        ("Spell + acronym",   "correct + expand",   ACCENT_AMBER),
        ("Graph filter",      "allow-list scope",   ACCENT_VIOLET),
        ("Hybrid retrieval",  "BM25 + dense + KG",  ACCENT_CYAN),
        ("ACL filter",        "role-gated chunks",  ACCENT_COPPER),
        ("LLM answer",        "gpt-4o + citations", ACCENT_GREEN),
        ("Critic loop",       "PASS / retry / FAIL",ACCENT_AMBER),
        ("HITL gate",         "approve / reject",   ACCENT_RED),
    ]
    n = len(nodes)
    gap_x = 4
    node_w = (PAGE_W - 72 - gap_x * (n - 1)) / n
    node_h = 70
    node_y = 330
    for i, (label, sub, color) in enumerate(nodes):
        x = 36 + i * (node_w + gap_x)
        # box
        c.setFillColor(color)
        c.setStrokeColor(color)
        c.roundRect(x, node_y, node_w, node_h, 5, fill=1, stroke=1)
        # label
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 9.5)
        c.drawCentredString(x + node_w / 2, node_y + node_h - 22, label)
        c.setFont("Helvetica", 8)
        c.drawCentredString(x + node_w / 2, node_y + node_h - 36, sub)
        # step number
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 7)
        c.drawCentredString(x + 12, node_y + node_h - 10, f"{i+1}")
        # arrow into next
        if i < n - 1:
            ax1 = x + node_w
            ax2 = ax1 + gap_x
            arrow_horizontal(c, ax1 + 1, node_y + node_h / 2, ax2 - 1,
                             color=INK_MID, width=1.0)

    # split-flow callouts below: critic PASS vs HITL pause
    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(36, node_y - 20,
                 "Branches AFTER the critic:")
    branches = [
        ("PASS  \u2192 deliver answer with citations",
         "Auto-approve if risk score < 0.6 and not a safety / purchase keyword.",
         ACCENT_GREEN),
        ("HITL  \u2192 pause + route to required role(s)",
         "criticality_classifier inspects the query for safety / $-tier / single-source / class-A signals.",
         ACCENT_RED),
        ("AUDIT  \u2192 write decision + drivers to immutable log",
         "Every approval / rejection is replayable. SOX-friendly evidence chain.",
         ACCENT_BLUE),
    ]
    branch_y = node_y - 30
    branch_h = 56
    branch_w = (PAGE_W - 72 - 24) / 3
    for i, (t, body, color) in enumerate(branches):
        x = 36 + i * (branch_w + 12)
        c.setFillColor(CARD_FILL)
        c.setStrokeColor(color)
        c.setLineWidth(0.8)
        c.roundRect(x, branch_y - branch_h, branch_w, branch_h, 5, fill=1, stroke=1)
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x + 12, branch_y - 18, t)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8.5)
        c.drawString(x + 12, branch_y - 34, body)

    # bottom stats
    stats = [
        ("Latency p50", "2.4 s", "diagnostic mode (cold cache: 4.5 s)"),
        ("LLM cost", "~$0.008", "per query, gpt-4o answer + qwen2.5 critic"),
        ("Hallucination", "~8%", "vs. ~25% classical RAG, ~40% direct LLM"),
        ("Auto-approve", "~74%", "of queries clear without HITL pause"),
    ]
    stat_w = (PAGE_W - 72 - 36) / 4
    stat_y = 70
    for i, (k, v, sub) in enumerate(stats):
        x = 36 + i * (stat_w + 12)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(x, stat_y + 30, k.upper())
        c.setFillColor(ACCENT_COPPER)
        c.setFont("Helvetica-Bold", 20)
        c.drawString(x, stat_y + 8, v)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 7.8)
        c.drawString(x, stat_y - 6, sub)

    slide_footer(c, "Slide 5 \u2014 How It Works")


# ─── Slide 6: System architecture ───────────────────────────────────────────


def slide6(c):
    slide_bg(c)
    brand_strip(c, slide_num=6, total=12)
    slide_title(
        c, "06", "System Architecture",
        "Six layers \u2014 every box is a real module in the repo, every line is an "
        "interaction contract in the 7-page architecture PDF.",
    )

    # Six horizontal layer rows
    layers = [
        {
            "title": "1. CLIENT",
            "boxes": [("Next.js 14 (chat + dashboards)", ACCENT_BLUE),
                      ("Streamlit (operator console)",   ACCENT_BLUE),
                      ("REST / CLI clients",             ACCENT_BLUE)],
            "color": ACCENT_BLUE,
        },
        {
            "title": "2. API",
            "boxes": [("FastAPI \u00b7 14 endpoints",     ACCENT_AMBER),
                      ("Auth (bearer + RBAC)",            ACCENT_AMBER),
                      ("ContextVar role propagation",     ACCENT_AMBER)],
            "color": ACCENT_AMBER,
        },
        {
            "title": "3. ORCHESTRATION",
            "boxes": [("LangGraph StateGraph",            ACCENT_GREEN),
                      ("HITL interrupt + checkpointer",   ACCENT_GREEN),
                      ("ChatAgent (slot-fill state machine)", ACCENT_GREEN)],
            "color": ACCENT_GREEN,
        },
        {
            "title": "4. REASONING",
            "boxes": [("ClarifierAgent + QueryCorrector", ACCENT_VIOLET),
                      ("Hybrid retriever (BM25 + dense + KG)", ACCENT_VIOLET),
                      ("Critic LLM + cause ranker",        ACCENT_VIOLET)],
            "color": ACCENT_VIOLET,
        },
        {
            "title": "5. KNOWLEDGE",
            "boxes": [("FAISS index (613 chunks, 384-dim)", ACCENT_CYAN),
                      ("NetworkX KG (501 nodes / 884 edges)", ACCENT_CYAN),
                      ("Document ACL (3 tiers)",             ACCENT_CYAN)],
            "color": ACCENT_CYAN,
        },
        {
            "title": "6. PERSISTENCE",
            "boxes": [("SQLite audit log (immutable)",     ACCENT_COPPER),
                      ("SQLite auth store (bearer tokens)", ACCENT_COPPER),
                      ("LangGraph checkpointer (SQLite / Memory)", ACCENT_COPPER)],
            "color": ACCENT_COPPER,
        },
    ]
    layer_label_w = 110
    n_boxes = 3
    box_gap = 8
    layer_h = 48
    layer_gap = 5
    box_w = (PAGE_W - 72 - layer_label_w - 16 - (n_boxes - 1) * box_gap) / n_boxes
    layer_y = PAGE_H - 130 - layer_h
    for layer in layers:
        # label band
        c.setFillColor(layer["color"])
        c.setStrokeColor(layer["color"])
        c.roundRect(36, layer_y, layer_label_w, layer_h, 4, fill=1, stroke=1)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(36 + 12, layer_y + layer_h - 22, layer["title"])

        # boxes
        bx = 36 + layer_label_w + 16
        for label, color in layer["boxes"]:
            c.setFillColor(CARD_FILL)
            c.setStrokeColor(color)
            c.setLineWidth(0.8)
            c.roundRect(bx, layer_y, box_w, layer_h, 4, fill=1, stroke=1)
            c.setFillColor(INK)
            c.setFont("Helvetica-Bold", 9)
            c.drawString(bx + 12, layer_y + layer_h - 22, label)
            bx += box_w + box_gap
        layer_y -= layer_h + layer_gap

    # Cross-cutting concerns ribbon
    ribbon_y = 78
    ribbon_h = 50
    c.setFillColor(INK_DARK)
    c.setStrokeColor(INK_DARK)
    c.roundRect(36, ribbon_y, PAGE_W - 72, ribbon_h, 6, fill=1, stroke=1)
    c.setFillColor(HexColor("#F59E0B"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(48, ribbon_y + ribbon_h - 18, "Cross-cutting:")
    c.setFillColor(white)
    c.setFont("Helvetica", 9)
    c.drawString(140, ribbon_y + ribbon_h - 18,
                 "Observability (timings per node, token spend) \u00b7 Config-driven LLM "
                 "routing (cheap critic / expensive answerer) \u00b7 Hot-reload of FAISS")
    c.setFillColor(HexColor("#F59E0B"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(48, ribbon_y + 14, "Quality gates:")
    c.setFillColor(white)
    c.setFont("Helvetica", 9)
    c.drawString(140, ribbon_y + 14,
                 "scripts/smoke_test_hitl.py (5/5) \u00b7 scripts/smoke_test_acl.py (5/5) "
                 "\u00b7 deterministic for CI before any prompt change ships")

    slide_footer(c, "Slide 6 \u2014 System Architecture")


# ─── Slide 7: Approvals + ACLs ──────────────────────────────────────────────


def slide7(c):
    slide_bg(c)
    brand_strip(c, slide_num=7, total=12)
    slide_title(
        c, "07", "Built-in Safety  \u2014  Maker-Checker + Document ACLs",
        "Two independent guardrails that already meet SOX-style segregation-of-duties "
        "and least-privilege requirements.",
    )

    # LEFT: HITL maker-checker block
    left_x = 36
    left_w = (PAGE_W - 72 - 24) / 2
    panel_top = PAGE_H - 130
    panel_h = panel_top - 130
    panel_y = panel_top - panel_h

    c.setFillColor(CARD_FILL)
    c.setStrokeColor(RULE)
    c.roundRect(left_x, panel_y, left_w, panel_h, 6, fill=1, stroke=1)
    c.setFillColor(ACCENT_GREEN)
    c.rect(left_x, panel_top - 4, left_w, 4, fill=1, stroke=0)

    c.setFillColor(ACCENT_GREEN)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left_x + 14, panel_top - 22, "MAKER-CHECKER  /  HITL APPROVAL GATE")
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(left_x + 14, panel_top - 44,
                 "An operator can never rubber-stamp their own escalation.")

    # role catalogue with maker/checker tags
    roles = [
        ("operator",              "maker",  ACCENT_RED),
        ("shift_supervisor",      "checker", ACCENT_GREEN),
        ("maintenance_planner",   "checker", ACCENT_GREEN),
        ("maintenance_engineer",  "checker", ACCENT_GREEN),
        ("ehs_officer",           "checker", ACCENT_GREEN),
        ("quality_engineer",      "checker", ACCENT_GREEN),
        ("buyer",                 "checker", ACCENT_GREEN),
        ("procurement_manager",   "checker", ACCENT_GREEN),
        ("plant_manager",         "checker", ACCENT_GREEN),
    ]
    role_y = panel_top - 70
    for r, tag, color in roles:
        c.setFillColor(INK)
        c.setFont("Helvetica", 9)
        c.drawString(left_x + 24, role_y, "\u2022  " + r)
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 7)
        c.drawString(left_x + left_w - 60, role_y, tag.upper())
        role_y -= 14

    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Oblique", 8.5)
    c.drawString(left_x + 14, panel_y + 18,
                 "Routes computed by required_roles_for(drivers) \u2014 e.g. \u201chot work\u201d "
                 "needs EHS + maintenance + plant manager.")

    # RIGHT: Document ACL
    right_x = left_x + left_w + 24
    right_w = left_w
    c.setFillColor(CARD_FILL)
    c.setStrokeColor(RULE)
    c.roundRect(right_x, panel_y, right_w, panel_h, 6, fill=1, stroke=1)
    c.setFillColor(ACCENT_VIOLET)
    c.rect(right_x, panel_top - 4, right_w, 4, fill=1, stroke=0)

    c.setFillColor(ACCENT_VIOLET)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(right_x + 14, panel_top - 22, "DOCUMENT ACL  /  ROLE-BASED KNOWLEDGE")
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(right_x + 14, panel_top - 44,
                 "The corpus itself is gated \u2014 not just the prompt.")

    tiers = [
        ("public",       "every role (incl. operators)",
         "SOPs, alarm responses, equipment manuals", HexColor("#15803D")),
        ("restricted",   "every checker role",
         "RCAs, regulatory playbooks, work orders",  HexColor("#B45309")),
        ("confidential", "plant_manager + procurement_manager",
         "financial review, M&A, supplier pricing",  HexColor("#B91C1C")),
    ]
    tier_y = panel_top - 70
    for tid, who, examples, col in tiers:
        # tier pill
        chip(c, right_x + 14, tier_y - 6, 78, 16, tid.upper(), col)
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", 8.5)
        c.drawString(right_x + 100, tier_y + 2, "Who: " + who)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8.5)
        c.drawString(right_x + 100, tier_y - 10, "What: " + examples)
        tier_y -= 36

    # proof point
    c.setFillColor(INK_DARK)
    proof_y = panel_y + 14
    c.rect(right_x + 14, proof_y, right_w - 28, 36, fill=1, stroke=0)
    c.setFillColor(HexColor("#86EFAC"))
    c.setFont("Helvetica-Bold", 8.5)
    c.drawString(right_x + 24, proof_y + 22,
                 'Proof: same query "Project Meridian acquisition target":')
    c.setFillColor(white)
    c.setFont("Helvetica", 8.5)
    c.drawString(right_x + 24, proof_y + 9,
                 "operator: 0 confidential chunks  \u00b7  plant_manager: full M&A diligence paper")

    slide_footer(c, "Slide 7 \u2014 Built-in Safety")


# ─── Slide 8: Plant data sources ────────────────────────────────────────────


def slide8(c):
    slide_bg(c)
    brand_strip(c, slide_num=8, total=12)
    slide_title(
        c, "08", "Plant Data Sources  \u2014  Already Ingested",
        "The PoC is already grounded in the document types every plant produces. "
        "Pointing at your corpus is a 1-week sprint, not a science project.",
    )

    # Top row: file-type chips with counts (illustrative)
    chips_data = [
        ("PDF manuals",      "ITM-001 quality manual,\nsafety/compliance reports",
         ACCENT_RED,    "\ud83d\udcd6"),
        ("TXT SOPs",         "CNC machining, supply\nchain procedures",
         ACCENT_GREEN,  "\ud83d\udcdd"),
        ("Excel work orders","Maximo/SAP-PM exports\nwith RCA + cost fields",
         ACCENT_BLUE,   "\ud83d\udcca"),
        ("Excel alarm log",  "PI / OSIsoft AF historian\nexport with severity",
         ACCENT_AMBER,  "\ud83d\udea8"),
        ("Excel spare parts","Inventory + lead-time\n+ vendor mapping",
         ACCENT_CYAN,   "\ud83d\udd27"),
        ("Production KPIs",  "OEE / scrap / cycle\ntime per line",
         ACCENT_VIOLET, "\ud83d\udcc8"),
    ]
    n = len(chips_data)
    card_w = (PAGE_W - 72 - (n - 1) * 12) / n
    card_h = 140
    card_y = 260
    for i, (title, body, color, icon) in enumerate(chips_data):
        x = 36 + i * (card_w + 12)
        # body
        c.setFillColor(CARD_FILL)
        c.setStrokeColor(color)
        c.setLineWidth(1.2)
        c.roundRect(x, card_y, card_w, card_h, 6, fill=1, stroke=1)
        # top stripe
        c.setFillColor(color)
        c.rect(x, card_y + card_h - 4, card_w, 4, fill=1, stroke=0)
        # icon
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 22)
        c.drawString(x + 12, card_y + card_h - 36, icon)
        # title
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x + 12, card_y + card_h - 60, title)
        # body
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8.5)
        line_y = card_y + card_h - 76
        for line in body.split("\n"):
            c.drawString(x + 12, line_y, line)
            line_y -= 11

    # Bottom: classification distribution stats
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(36, 225, "Current PoC index breakdown")

    stats = [
        ("Total chunks",        "613",   "public 569 \u00b7 restricted 16 \u00b7 confidential 28", INK_DARK),
        ("Source documents",    "13",    "PDFs, TXT SOPs, Excel \u2014 ingested via recursive parse", ACCENT_BLUE),
        ("KG nodes / edges",    "501 / 884", "Equipment, Symptom, Procedure, SparePart, Alarm, FailureMode", ACCENT_GREEN),
        ("Embedding model",     "MiniLM-L6", "384-dim, fast on CPU; swap to E5-Large for higher recall", ACCENT_AMBER),
    ]
    sw = (PAGE_W - 72 - 36) / 4
    sy = 95
    for i, (k, v, sub, color) in enumerate(stats):
        x = 36 + i * (sw + 12)
        c.setFillColor(color)
        c.setStrokeColor(color)
        c.setLineWidth(0.8)
        c.roundRect(x, sy, sw, 110, 6, fill=0, stroke=1)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(x + 12, sy + 110 - 16, k.upper())
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(x + 12, sy + 110 - 48, v)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8)
        # wrap subtitle if too long
        words = sub.split()
        lines = []
        cur = ""
        for w in words:
            if len(cur) + len(w) > 36:
                lines.append(cur.strip())
                cur = ""
            cur += w + " "
        if cur:
            lines.append(cur.strip())
        ly = sy + 110 - 70
        for line in lines:
            c.drawString(x + 12, ly, line)
            ly -= 11

    slide_footer(c, "Slide 8 \u2014 Plant Data Sources")


# ─── Slide 9: Extensibility / agentic connectors ────────────────────────────


def slide9(c):
    slide_bg(c)
    brand_strip(c, slide_num=9, total=12)
    slide_title(
        c, "09", "Extensibility  \u2014  Agentic Connectors to ERP / SAP / MES",
        "The same pipeline answers from live systems-of-record via a thin "
        "tool-calling agent layer. The chat doesn\u2019t change. The reach does.",
    )

    # ── Two-column architecture diagram ─────────────────────────────────────
    # Left: the existing read-only RAG path (already shipped).
    # Right: the proposed agent layer with connectors.
    # In between: a vertical "Agent Router" pillar that the LangGraph
    # orchestrator dispatches tool calls through.

    # Vertical bands
    band_top = PAGE_H - 130
    band_h = band_top - 130
    band_y = band_top - band_h

    left_w = 200
    right_w = 290
    middle_w = 170
    gap = 18
    total_w = left_w + middle_w + right_w + gap * 2
    base_x = (PAGE_W - total_w) / 2

    # Left: RAG path
    c.setFillColor(CARD_FILL)
    c.setStrokeColor(ACCENT_CYAN)
    c.setLineWidth(1.2)
    c.roundRect(base_x, band_y, left_w, band_h, 6, fill=1, stroke=1)
    c.setFillColor(ACCENT_CYAN)
    c.rect(base_x, band_top - 4, left_w, 4, fill=1, stroke=0)
    c.setFillColor(ACCENT_CYAN)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(base_x + 12, band_top - 22, "TODAY  \u2014  RAG PATH (read-only)")
    left_items = [
        "FAISS + BM25 + Knowledge Graph",
        "Plant SOPs, manuals, work orders,",
        "alarm history, financials (ACL-gated)",
        "Critic-checked, citation-grounded",
        "answers in 2-4 s",
    ]
    item_y = band_top - 42
    c.setFillColor(INK)
    c.setFont("Helvetica", 9)
    for line in left_items:
        c.drawString(base_x + 14, item_y, "\u2022  " + line)
        item_y -= 14

    # Middle: Agent Router
    mid_x = base_x + left_w + gap
    c.setFillColor(INK_DARK)
    c.setStrokeColor(INK_DARK)
    c.roundRect(mid_x, band_y, middle_w, band_h, 6, fill=1, stroke=1)
    c.setFillColor(ACCENT_AMBER)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(mid_x + 12, band_top - 22, "AGENT ROUTER (new)")
    c.setFillColor(white)
    c.setFont("Helvetica", 8.5)
    body_lines = [
        "LangGraph tool node",
        "decides per turn:",
        "",
        "  read corpus   \u2192 RAG",
        "  fetch record  \u2192 ERP tool",
        "  post action   \u2192 ERP tool",
        "  query db      \u2192 SQL tool",
        "",
        "Every tool call:",
        "  \u00b7 typed input schema",
        "  \u00b7 RBAC + ACL pre-check",
        "  \u00b7 audit log write",
        "  \u00b7 critic post-check",
    ]
    item_y = band_top - 42
    for line in body_lines:
        c.drawString(mid_x + 14, item_y, line)
        item_y -= 11.5

    # Right: external connectors
    right_x = mid_x + middle_w + gap
    c.setFillColor(CARD_FILL)
    c.setStrokeColor(ACCENT_COPPER)
    c.setLineWidth(1.2)
    c.roundRect(right_x, band_y, right_w, band_h, 6, fill=1, stroke=1)
    c.setFillColor(ACCENT_COPPER)
    c.rect(right_x, band_top - 4, right_w, 4, fill=1, stroke=0)
    c.setFillColor(ACCENT_COPPER)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(right_x + 12, band_top - 22,
                 "TOMORROW  \u2014  ENTERPRISE CONNECTORS")

    connectors = [
        ("SAP S/4HANA",       "OData + RFC. Read PR/PO,\npost goods receipts, query MM/PM.",      ACCENT_AMBER),
        ("SAP PM / Maximo",   "Pull active work orders,\ncreate notifications, close jobs.",     ACCENT_BLUE),
        ("Oracle / MS-Dynamics", "OData / SOAP. Vendor master,\nGL postings, AP three-way match.", ACCENT_GREEN),
        ("MES (Wonderware, Ignition)", "OPC-UA / SQL. Live shop-floor\ntags, OEE, batch records.",ACCENT_VIOLET),
        ("Historian (PI / Aveva)", "PI Web API. Real-time alarms,\nvibration / temperature trends.", ACCENT_RED),
        ("Postgres / Snowflake", "Read-only views over the data\nwarehouse \u2014 quality, scrap, cost.", ACCENT_CYAN),
    ]
    ent_y = band_top - 42
    for name, body, col in connectors:
        # name pill
        c.setFillColor(col)
        c.setStrokeColor(col)
        c.roundRect(right_x + 14, ent_y - 4, 130, 18, 4, fill=1, stroke=1)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(right_x + 22, ent_y + 4, name)
        # body
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8)
        for j, line in enumerate(body.split("\n")):
            c.drawString(right_x + 152, ent_y + 6 - j * 10, line)
        ent_y -= 28

    # Arrows: left↔mid, mid↔right
    arrow_y = band_y + band_h / 2
    arrow_horizontal(c, base_x + left_w + 2, arrow_y, mid_x - 2,
                     color=INK_MID, width=1.3)
    arrow_horizontal(c, mid_x + middle_w + 2, arrow_y, right_x - 2,
                     color=INK_MID, width=1.3)

    # Bottom ribbon: extensibility principles
    ribbon_y = 78
    ribbon_h = 46
    c.setFillColor(INK_DARK)
    c.setStrokeColor(INK_DARK)
    c.roundRect(36, ribbon_y, PAGE_W - 72, ribbon_h, 6, fill=1, stroke=1)
    c.setFillColor(ACCENT_AMBER)
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(48, ribbon_y + ribbon_h - 18,
                 "Every connector follows the same 4-rule contract:")
    c.setFillColor(white)
    c.setFont("Helvetica", 9)
    c.drawString(48, ribbon_y + 14,
                 "(1) Typed Pydantic schema   "
                 "(2) RBAC + document-ACL pre-check before any external call   "
                 "(3) HITL gate on writes / state-changing actions   "
                 "(4) Append-only audit row with full request + response payload")

    slide_footer(c, "Slide 9 \u2014 Extensibility")


# ─── Slide 10: Concrete use cases ───────────────────────────────────────────


def slide10(c):
    slide_bg(c)
    brand_strip(c, slide_num=10, total=12)
    slide_title(
        c, "10", "Concrete Plant Use Cases",
        "Six demonstrable workflows already in the PoC \u2014 each one shaves minutes off "
        "a real shop-floor decision.",
    )

    use_cases = [
        {
            "role":    "Maintenance technician",
            "query":   '"Pump P-203 high vibration alarm ALM-P001 \u2014 likely cause and fix?"',
            "answer":  "Bearing inner-race spalling. SOP page 12, work order WO-2024-031 (4.6 h MTTR).",
            "value":   "MTTR cut by 30-50%",
            "color":   ACCENT_BLUE,
            "tools":   "RAG + KG",
        },
        {
            "role":    "Shift supervisor",
            "query":   '"Hot work permit for tank T-9 \u2014 emergency shutdown."',
            "answer":  "Paused at HITL gate. Routed to EHS officer + maintenance engineer + plant manager.",
            "value":   "Zero permit-related incidents",
            "color":   ACCENT_RED,
            "tools":   "HITL gate",
        },
        {
            "role":    "Operator",
            "query":   '"Raise a PO for 5 BRG-7203 bearings at $5,000 from vendor SKF urgent."',
            "answer":  "Parsed into purchase_request payload. Routed to buyer (\u2264$10k tier).",
            "value":   "P2P cycle 8 days \u2192 2 days",
            "color":   ACCENT_AMBER,
            "tools":   "RAG + agent (SAP MM)",
        },
        {
            "role":    "Quality engineer",
            "query":   '"Show RCA cluster for the Q4 spindle-bearing failures \u2014 are CAPAs verified?"',
            "answer":  "3 CAPAs all VERIFIED Feb 2026. Returns chunks from internal_incident_rca_2025_q4.txt.",
            "value":   "Audit prep 1 week \u2192 1 hour",
            "color":   ACCENT_VIOLET,
            "tools":   "RAG + ACL (restricted)",
        },
        {
            "role":    "Procurement manager",
            "query":   '"Compare strategic supplier rebate tiers for SKF, Siemens, Sandvik."',
            "answer":  "Rebate tier table summarised. Confidential pricing only visible to procurement.",
            "value":   "Sourcing cycle -40%",
            "color":   ACCENT_GREEN,
            "tools":   "RAG + ACL (confidential)",
        },
        {
            "role":    "Plant manager",
            "query":   '"What is Q1 2026 EBITDA and FY26 capex commitment?"',
            "answer":  "$7.9M EBITDA (18.5%). $4.6M committed of $18.0M envelope. Cites q1_2026_financial_review.txt.",
            "value":   "Board prep minutes, not days",
            "color":   ACCENT_COPPER,
            "tools":   "RAG + ACL (confidential)",
        },
    ]

    card_w = (PAGE_W - 72 - 24) / 3
    card_h = 145
    base_y = PAGE_H - 290
    for i, uc in enumerate(use_cases):
        col = i % 3
        row = i // 3
        x = 36 + col * (card_w + 12)
        y = base_y - row * (card_h + 12)

        c.setFillColor(CARD_FILL)
        c.setStrokeColor(uc["color"])
        c.setLineWidth(0.9)
        c.roundRect(x, y, card_w, card_h, 6, fill=1, stroke=1)
        c.setFillColor(uc["color"])
        c.rect(x, y + card_h - 4, card_w, 4, fill=1, stroke=0)

        # role tag
        c.setFillColor(uc["color"])
        c.setFont("Helvetica-Bold", 8.5)
        c.drawString(x + 12, y + card_h - 22, uc["role"].upper())
        # tools tag (right)
        c.setFillColor(INK_MID)
        c.setFont("Helvetica-Oblique", 7.5)
        c.drawRightString(x + card_w - 12, y + card_h - 22, uc["tools"])
        # query
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", 9.5)
        # word wrap the query
        text = uc["query"]
        wrapped = _wrap(text, 50)
        line_y = y + card_h - 40
        for line in wrapped:
            c.drawString(x + 12, line_y, line)
            line_y -= 12
        # answer
        c.setFillColor(INK_MID)
        c.setFont("Helvetica", 8.5)
        ans_wrapped = _wrap(uc["answer"], 58)
        for line in ans_wrapped:
            c.drawString(x + 12, line_y, line)
            line_y -= 11

        # value chip
        chip_y = y + 12
        c.setFillColor(uc["color"])
        c.setStrokeColor(uc["color"])
        c.roundRect(x + 12, chip_y, card_w - 24, 16, 8, fill=1, stroke=1)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(x + card_w / 2, chip_y + 4, uc["value"])

    slide_footer(c, "Slide 10 \u2014 Plant Use Cases")


def _wrap(text: str, max_chars: int) -> list[str]:
    """Tiny word-wrap helper for use-case cards."""
    words = text.split()
    lines: list[str] = []
    cur = ""
    for w in words:
        if len(cur) + len(w) + 1 > max_chars and cur:
            lines.append(cur)
            cur = w
        else:
            cur = (cur + " " + w).strip()
    if cur:
        lines.append(cur)
    return lines


# ─── Slide 11: Business impact ──────────────────────────────────────────────


def slide11(c):
    slide_bg(c)
    brand_strip(c, slide_num=11, total=12)
    slide_title(
        c, "11", "Business Impact  \u2014  Where the Money Lives",
        "An illustrative model for a single mid-size plant with 100,000 AI-assisted "
        "decisions per month. Calibrated to your baseline in Week 1.",
    )

    # Top row: 4 big hero numbers
    heroes = [
        {
            "title": "DOWNTIME AVOIDED",
            "value": "$5.4M",
            "body": [
                "per month, at a $260K/hr line rate",
                "and 20 prevented unplanned stops.",
                "Driven by faster RCA + spare lookup.",
            ],
            "accent": ACCENT_GREEN,
        },
        {
            "title": "MTTR REDUCTION",
            "value": "-35%",
            "body": [
                "Cited evidence + KG cross-refs",
                "cut diagnosis time from 47 min",
                "to ~30 min on top-20 failures.",
            ],
            "accent": ACCENT_BLUE,
        },
        {
            "title": "WRONG-ANSWER COST",
            "value": "-68%",
            "body": [
                "Hallucination ~25% (classical RAG)",
                "\u2192 ~8% with critic + HITL.",
                "At $300/error \u00b7 100K queries: $5.1M/mo.",
            ],
            "accent": ACCENT_COPPER,
        },
        {
            "title": "AUDIT EXPOSURE",
            "value": "-90%",
            "body": [
                "Every decision has a provenance",
                "trail \u2014 chunk citations, RBAC role,",
                "approver, comments, timestamp.",
            ],
            "accent": ACCENT_VIOLET,
        },
    ]
    n = len(heroes)
    card_w = (PAGE_W - 72 - (n - 1) * 12) / n
    card_h = 170
    card_y = 270
    for i, h in enumerate(heroes):
        x = 36 + i * (card_w + 12)
        callout_card(c, x, card_y, card_w, card_h,
                     title=h["title"], value=h["value"], body=h["body"],
                     accent=h["accent"], value_size=28, body_size=9)

    # Bottom: a small ROI math table
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(36, 235, "The math  \u2014  per plant, per month, illustrative")

    headers = ["Line item", "Direct LLM", "Classical RAG", "Hybrid GraphRAG"]
    rows = [
        ("LLM tokens / month",                "$2,000",   "$2,500",   "$4,100"),
        ("Wrong-answer cost ($300/error)",    "$12.0M",   "$7.5M",    "$2.4M"),
        ("Downtime cost (lookups + RCA)",     "$8.0M",    "$6.5M",    "$2.6M"),
        ("Audit / compliance reserve",        "$0.8M",    "$0.5M",    "$0.05M"),
        ("TOTAL",                             "$20.8M",   "$14.5M",   "$5.1M"),
        ("vs Hybrid GraphRAG",                "+$15.7M",  "+$9.4M",   "\u2014"),
    ]
    col_widths = [330, 170, 170, 220]
    table(c, 36, 220, headers, rows, col_widths,
          row_h=18, header_h=22, header_font_size=9, body_font_size=9,
          highlight_col=3)

    c.setFillColor(INK_MID)
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(36, 70,
                 "Numbers are illustrative based on PoC eval + plant-cost industry medians "
                 "(Deloitte, ARC Advisory). The pilot Week-1-2 sprint replaces every cell with "
                 "your plant\u2019s actuals.")

    slide_footer(c, "Slide 11 \u2014 Business Impact")


# ─── Slide 12: Pilot plan ───────────────────────────────────────────────────


def slide12(c):
    slide_bg(c)
    brand_strip(c, slide_num=12, total=12)
    slide_title(
        c, "12", "What We Propose  \u2014  10-Week Pilot",
        "A scoped pilot on YOUR plant data. Ship the operator chat at L3 in 6 weeks. "
        "Production trust at L4 in 10.",
    )

    phases = [
        {
            "label":  "PHASE 1  \u00b7  DISCOVERY",
            "weeks":  "Week 1",
            "accent": ACCENT_BLUE,
            "items":  [
                "Domain workshop \u2014 personas, risk profile,",
                "  10-30 real plant queries, source inventory.",
                "Seed ontology + driver-to-role policy.",
                "Gold evaluation set drafted (\u2265 50 Q\u2192A pairs).",
            ],
        },
        {
            "label":  "PHASE 2  \u00b7  BUILD",
            "weeks":  "Weeks 2-5",
            "accent": ACCENT_AMBER,
            "items":  [
                "Connect SOP / WO / alarm / SAP exports.",
                "Tune classification tiers + RBAC.",
                "Stand up FAISS + KG + critic on YOUR data.",
                "L3 baseline live for 5-10 pilot users.",
                "First eval report \u2192 calibrate thresholds.",
            ],
        },
        {
            "label":  "PHASE 3  \u00b7  VALIDATE",
            "weeks":  "Weeks 6-10",
            "accent": ACCENT_GREEN,
            "items":  [
                "Expert validation \u00b7 critic calibration.",
                "First ERP / Maximo agent connector wired up.",
                "Gold-set acceptance + handover docs.",
                "L4 production-quality \u2014 sign-off for prod.",
                "Decision: scale to next plant / next domain.",
            ],
        },
    ]
    phase_w = (PAGE_W - 72 - 24) / 3
    phase_h = 235
    phase_y = 175
    for i, ph in enumerate(phases):
        x = 36 + i * (phase_w + 12)
        c.setFillColor(CARD_FILL)
        c.setStrokeColor(ph["accent"])
        c.setLineWidth(1.2)
        c.roundRect(x, phase_y, phase_w, phase_h, 6, fill=1, stroke=1)
        c.setFillColor(ph["accent"])
        c.rect(x, phase_y + phase_h - 4, phase_w, 4, fill=1, stroke=0)

        c.setFillColor(ph["accent"])
        c.setFont("Helvetica-Bold", 11)
        c.drawString(x + 14, phase_y + phase_h - 24, ph["label"])
        c.setFillColor(INK_MID)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x + 14, phase_y + phase_h - 42, ph["weeks"])

        c.setFillColor(INK)
        c.setFont("Helvetica", 9.5)
        line_y = phase_y + phase_h - 62
        for it in ph["items"]:
            c.drawString(x + 14, line_y, "\u2022  " + it if not it.startswith("  ") else "      " + it.strip())
            line_y -= 14

    # CTA ribbon
    ribbon_y = 60
    ribbon_h = 90
    c.setFillColor(INK_DARK)
    c.setStrokeColor(INK_DARK)
    c.roundRect(36, ribbon_y, PAGE_W - 72, ribbon_h, 8, fill=1, stroke=1)

    c.setFillColor(ACCENT_COPPER)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(54, ribbon_y + ribbon_h - 26, "NEXT STEP  \u2014  60-minute Discovery Workshop")

    c.setFillColor(white)
    c.setFont("Helvetica", 10)
    c.drawString(54, ribbon_y + ribbon_h - 46,
                 "We arrive with the demo running on a laptop. You bring 5 SOPs, 30 work orders, "
                 "and the people who use them every day.")

    c.setFillColor(HexColor("#94A3B8"))
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(54, ribbon_y + 30,
                 "Agenda: 10 min context  \u00b7  20 min live demo  \u00b7  20 min source / persona walkthrough"
                 "  \u00b7  10 min pilot scope + go/no-go.")
    c.setFillColor(HexColor("#94A3B8"))
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(54, ribbon_y + 14,
                 "Deliverable: a 1-page pilot SOW you can sign off, with named owners on both sides.")

    # right-side decision ask
    c.setFillColor(ACCENT_COPPER)
    c.setFont("Helvetica-Bold", 22)
    c.drawRightString(PAGE_W - 54, ribbon_y + ribbon_h - 30, "Decide by")
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 28)
    c.drawRightString(PAGE_W - 54, ribbon_y + ribbon_h - 58, "Friday")

    slide_footer(c, "Slide 12 \u2014 The Pilot Plan")


# ─── Driver ─────────────────────────────────────────────────────────────────


def main():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(OUTPUT), pagesize=PAGE_SIZE)
    c.setTitle("Manufacturing Hybrid GraphRAG — Pitch Deck")
    c.setAuthor("hybrid-graphrag-manufacturing")
    c.setSubject(
        "12-slide business pitch for a manufacturing plant company. "
        "Problem, solution, architecture, extensibility, ROI, pilot plan."
    )

    pages = [
        slide1, slide2, slide3, slide4, slide5, slide6,
        slide7, slide8, slide9, slide10, slide11, slide12,
    ]
    for fn in pages:
        fn(c)
        c.showPage()

    c.save()
    print(f"Wrote: {OUTPUT}")


if __name__ == "__main__":
    main()
